import React, { useState, useEffect } from 'react';
import { FileText, ShieldAlert, Truck, RefreshCw, Layers, Save } from 'lucide-react';
import { logActivity } from '../../../services/activityLogger';
import { useToast } from '../../../hooks/useToast';

const STORAGE_KEY = 'erp_purchase_config';

const DEFAULT_CONFIG = {
  poPrefix: 'PO',
  poSeparator: '/',
  includeFinancialYear: true,
  nextPoNumber: 1001,
  grnPrefix: 'GRN',
  nextGrnNumber: 501,
  requirePoApproval: true,
  approvalThresholdAmount: 50000,
  defaultSupplierPaymentDueDays: 30,
  autoGenerateDebitNoteOnReturn: true,
  allowExcessReceiving: false,
  maxExcessReceivingPercent: 5,
  requireInvoiceMatching: true
};

export default function PurchaseConfig() {
  const toast = useToast();
  const [activeTab, setActiveTab] = useState('sequence');
  const [config, setConfig] = useState(DEFAULT_CONFIG);

  useEffect(() => {
    try {
      const stored = localStorage.getItem(STORAGE_KEY);
      if (stored) {
        setConfig(JSON.parse(stored));
      } else {
        localStorage.setItem(STORAGE_KEY, JSON.stringify(DEFAULT_CONFIG));
      }
    } catch (e) {
      console.error('Error fetching purchase config:', e);
    }
  }, []);

  const generatePreview = (type) => {
    const currentYear = new Date().getFullYear();
    const shortYear = currentYear.toString().slice(-2);
    const nextYearShort = (currentYear + 1).toString().slice(-2);
    const fyString = config.includeFinancialYear ? `20${shortYear}-${nextYearShort}` : '';
    
    const parts = [];
    if (type === 'po') {
      if (config.poPrefix) parts.push(config.poPrefix);
      if (fyString) parts.push(fyString);
      parts.push(config.nextPoNumber);
    } else {
      if (config.grnPrefix) parts.push(config.grnPrefix);
      if (fyString) parts.push(fyString);
      parts.push(config.nextGrnNumber);
    }

    return parts.join(config.poSeparator || '');
  };

  const handleSave = () => {
    try {
      localStorage.setItem(STORAGE_KEY, JSON.stringify(config));
      
      logActivity({
        activityType: 'UPDATE',
        module: 'Purchase Settings',
        actionDescription: 'Updated Purchase configuration and approval rules.',
        newValue: config
      });

      toast.showSuccess('Success', 'Purchase configurations saved successfully!');
    } catch (e) {
      toast.showError('Error', 'Unable to save purchase configurations.');
    }
  };

  const handleResetDefaults = () => {
    if (window.confirm('Reset all purchase settings to standard defaults?')) {
      setConfig(DEFAULT_CONFIG);
      toast.showInfo('Reset Completed', 'Purchase settings restored to factory defaults.');
    }
  };

  const tabs = [
    { id: 'sequence', label: 'PO & GRN Sequence', icon: FileText },
    { id: 'approval', label: 'Approval Workflow', icon: ShieldAlert },
    { id: 'supplier', label: 'Supplier Defaults', icon: Truck },
    { id: 'return', label: 'Purchase Returns', icon: RefreshCw },
    { id: 'receiving', label: 'Receiving Rules', icon: Layers }
  ];

  return (
    <div style={{ display: 'flex', gap: '24px', flexWrap: 'wrap', paddingBottom: '60px' }} className="purchase-config-layout">
      
      {/* Navigation Tabs */}
      <div style={{
        width: '260px',
        display: 'flex',
        flexDirection: 'column',
        gap: '8px',
        background: '#ffffff',
        padding: '16px',
        borderRadius: '16px',
        border: '1px solid #e5e7eb',
        alignSelf: 'flex-start'
      }} className="purchase-config-left">
        {tabs.map(tab => {
          const Icon = tab.icon;
          return (
            <button
              key={tab.id}
              onClick={() => setActiveTab(tab.id)}
              style={{
                display: 'flex',
                alignItems: 'center',
                gap: '10px',
                padding: '12px 14px',
                borderRadius: '10px',
                border: 'none',
                background: activeTab === tab.id ? '#f5ebe1' : 'transparent',
                color: activeTab === tab.id ? '#7c7a6e' : '#4b5563',
                fontSize: '0.85rem',
                fontWeight: 600,
                textAlign: 'left',
                cursor: 'pointer',
                transition: 'all 0.2s'
              }}
            >
              <Icon size={16} />
              <span>{tab.label}</span>
            </button>
          );
        })}
      </div>

      {/* Main card viewport */}
      <div style={{
        flex: 1,
        background: '#ffffff',
        padding: '24px',
        borderRadius: '16px',
        border: '1px solid #e5e7eb',
        display: 'flex',
        flexDirection: 'column',
        gap: '24px'
      }}>
        
        {/* Render Sequence Tab */}
        {activeTab === 'sequence' && (
          <div style={{ display: 'flex', flexDirection: 'column', gap: '18px' }}>
            <h3 style={{ fontSize: '1rem', fontWeight: 700, color: '#374151', margin: 0, borderBottom: '1px solid #f3f4f6', paddingBottom: '8px' }}>
              Purchase Order & Goods Receipt Note Sequences
            </h3>
            
            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '16px' }} className="responsive-grid">
              <div style={{ background: '#fafafa', padding: '16px', borderRadius: '12px', border: '1px solid #f3f4f6' }}>
                <span style={{ fontSize: '0.75rem', color: '#9ca3af', textTransform: 'uppercase', fontWeight: 700 }}>Live PO Format Preview</span>
                <div style={{ fontSize: '1.2rem', fontWeight: 700, color: '#0369a1', marginTop: '6px', fontFamily: 'monospace' }}>
                  {generatePreview('po')}
                </div>
              </div>
              <div style={{ background: '#fafafa', padding: '16px', borderRadius: '12px', border: '1px solid #f3f4f6' }}>
                <span style={{ fontSize: '0.75rem', color: '#9ca3af', textTransform: 'uppercase', fontWeight: 700 }}>Live GRN Format Preview</span>
                <div style={{ fontSize: '1.2rem', fontWeight: 700, color: '#b45309', marginTop: '6px', fontFamily: 'monospace' }}>
                  {generatePreview('grn')}
                </div>
              </div>
            </div>

            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '16px' }} className="responsive-grid">
              <div style={{ display: 'flex', flexDirection: 'column', gap: '6px' }}>
                <label style={{ fontSize: '0.8rem', fontWeight: 600, color: '#4b5563' }}>PO Number Prefix</label>
                <input
                  type="text"
                  value={config.poPrefix}
                  onChange={(e) => setConfig(p => ({ ...p, poPrefix: e.target.value }))}
                  style={{ padding: '10px', fontSize: '0.875rem', borderRadius: '8px', border: '1px solid #e5e7eb', outline: 'none' }}
                />
              </div>
              <div style={{ display: 'flex', flexDirection: 'column', gap: '6px' }}>
                <label style={{ fontSize: '0.8rem', fontWeight: 600, color: '#4b5563' }}>GRN Number Prefix</label>
                <input
                  type="text"
                  value={config.grnPrefix}
                  onChange={(e) => setConfig(p => ({ ...p, grnPrefix: e.target.value }))}
                  style={{ padding: '10px', fontSize: '0.875rem', borderRadius: '8px', border: '1px solid #e5e7eb', outline: 'none' }}
                />
              </div>
            </div>

            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '16px' }} className="responsive-grid">
              <div style={{ display: 'flex', flexDirection: 'column', gap: '6px' }}>
                <label style={{ fontSize: '0.8rem', fontWeight: 600, color: '#4b5563' }}>Next PO Number</label>
                <input
                  type="number"
                  value={config.nextPoNumber}
                  onChange={(e) => setConfig(p => ({ ...p, nextPoNumber: parseInt(e.target.value) || 0 }))}
                  style={{ padding: '10px', fontSize: '0.875rem', borderRadius: '8px', border: '1px solid #e5e7eb', outline: 'none' }}
                />
              </div>
              <div style={{ display: 'flex', flexDirection: 'column', gap: '6px' }}>
                <label style={{ fontSize: '0.8rem', fontWeight: 600, color: '#4b5563' }}>Next GRN Number</label>
                <input
                  type="number"
                  value={config.nextGrnNumber}
                  onChange={(e) => setConfig(p => ({ ...p, nextGrnNumber: parseInt(e.target.value) || 0 }))}
                  style={{ padding: '10px', fontSize: '0.875rem', borderRadius: '8px', border: '1px solid #e5e7eb', outline: 'none' }}
                />
              </div>
            </div>

            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '16px' }} className="responsive-grid">
              <div style={{ display: 'flex', flexDirection: 'column', gap: '6px' }}>
                <label style={{ fontSize: '0.8rem', fontWeight: 600, color: '#4b5563' }}>Separator character</label>
                <input
                  type="text"
                  value={config.poSeparator}
                  onChange={(e) => setConfig(p => ({ ...p, poSeparator: e.target.value }))}
                  style={{ padding: '10px', fontSize: '0.875rem', borderRadius: '8px', border: '1px solid #e5e7eb', outline: 'none' }}
                />
              </div>

              <label style={{ display: 'flex', alignItems: 'center', gap: '8px', fontSize: '0.85rem', color: '#4b5563', cursor: 'pointer', marginTop: '24px' }}>
                <input
                  type="checkbox"
                  checked={config.includeFinancialYear}
                  onChange={(e) => setConfig(p => ({ ...p, includeFinancialYear: e.target.checked }))}
                  style={{ width: '16px', height: '16px', accentColor: '#7c7a6e' }}
                />
                <span>Include current Financial Year (e.g. 2026-27)</span>
              </label>
            </div>
          </div>
        )}

        {/* Approval Workflow Tab */}
        {activeTab === 'approval' && (
          <div style={{ display: 'flex', flexDirection: 'column', gap: '18px' }}>
            <h3 style={{ fontSize: '1rem', fontWeight: 700, color: '#374151', margin: 0, borderBottom: '1px solid #f3f4f6', paddingBottom: '8px' }}>
              Purchase Approval Workflows
            </h3>

            <label style={{ display: 'flex', alignItems: 'center', gap: '8px', fontSize: '0.85rem', color: '#4b5563', cursor: 'pointer' }}>
              <input
                type="checkbox"
                checked={config.requirePoApproval}
                onChange={(e) => setConfig(p => ({ ...p, requirePoApproval: e.target.checked }))}
                style={{ width: '16px', height: '16px', accentColor: '#7c7a6e' }}
              />
              <span>Require administrative approval before issuing purchase orders (POs)</span>
            </label>

            {config.requirePoApproval && (
              <div style={{ display: 'flex', flexDirection: 'column', gap: '6px', maxWidth: '50%', animation: 'fade-in 0.2s ease' }} className="full-width-mobile">
                <label style={{ fontSize: '0.8rem', fontWeight: 600, color: '#4b5563' }}>PO Approval Threshold Amount (₹)</label>
                <input
                  type="number"
                  value={config.approvalThresholdAmount}
                  onChange={(e) => setConfig(p => ({ ...p, approvalThresholdAmount: parseInt(e.target.value) || 0 }))}
                  style={{ padding: '10px', fontSize: '0.875rem', borderRadius: '8px', border: '1px solid #e5e7eb', outline: 'none' }}
                />
                <span style={{ fontSize: '0.725rem', color: '#9ca3af' }}>POs exceeding this value require a manager's confirmation.</span>
              </div>
            )}
          </div>
        )}

        {/* Supplier Defaults Tab */}
        {activeTab === 'supplier' && (
          <div style={{ display: 'flex', flexDirection: 'column', gap: '18px' }}>
            <h3 style={{ fontSize: '1rem', fontWeight: 700, color: '#374151', margin: 0, borderBottom: '1px solid #f3f4f6', paddingBottom: '8px' }}>
              Supplier Defaults
            </h3>

            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '16px' }} className="responsive-grid">
              <div style={{ display: 'flex', flexDirection: 'column', gap: '6px' }}>
                <label style={{ fontSize: '0.8rem', fontWeight: 600, color: '#4b5563' }}>Default Payment Due Period (Days)</label>
                <input
                  type="number"
                  value={config.defaultSupplierPaymentDueDays}
                  onChange={(e) => setConfig(p => ({ ...p, defaultSupplierPaymentDueDays: parseInt(e.target.value) || 0 }))}
                  style={{ padding: '10px', fontSize: '0.875rem', borderRadius: '8px', border: '1px solid #e5e7eb', outline: 'none' }}
                />
              </div>
            </div>
          </div>
        )}

        {/* Purchase Return Tab */}
        {activeTab === 'return' && (
          <div style={{ display: 'flex', flexDirection: 'column', gap: '18px' }}>
            <h3 style={{ fontSize: '1rem', fontWeight: 700, color: '#374151', margin: 0, borderBottom: '1px solid #f3f4f6', paddingBottom: '8px' }}>
              Purchase Return Policies
            </h3>

            <label style={{ display: 'flex', alignItems: 'center', gap: '8px', fontSize: '0.85rem', color: '#4b5563', cursor: 'pointer' }}>
              <input
                type="checkbox"
                checked={config.autoGenerateDebitNoteOnReturn}
                onChange={(e) => setConfig(p => ({ ...p, autoGenerateDebitNoteOnReturn: e.target.checked }))}
                style={{ width: '16px', height: '16px', accentColor: '#7c7a6e' }}
              />
              <span>Automatically generate corresponding Debit Note adjustments upon registering supplier returns</span>
            </label>
          </div>
        )}

        {/* Receiving Rules Tab */}
        {activeTab === 'receiving' && (
          <div style={{ display: 'flex', flexDirection: 'column', gap: '18px' }}>
            <h3 style={{ fontSize: '1rem', fontWeight: 700, color: '#374151', margin: 0, borderBottom: '1px solid #f3f4f6', paddingBottom: '8px' }}>
              Inventory Goods Receipt & Receiving Rules
            </h3>

            <div style={{ display: 'flex', flexDirection: 'column', gap: '12px' }}>
              <label style={{ display: 'flex', alignItems: 'center', gap: '8px', fontSize: '0.85rem', color: '#4b5563', cursor: 'pointer' }}>
                <input
                  type="checkbox"
                  checked={config.requireInvoiceMatching}
                  onChange={(e) => setConfig(p => ({ ...p, requireInvoiceMatching: e.target.checked }))}
                  style={{ width: '16px', height: '16px', accentColor: '#7c7a6e' }}
                />
                <span>Strict invoice item matching validation check during GRN entry</span>
              </label>

              <label style={{ display: 'flex', alignItems: 'center', gap: '8px', fontSize: '0.85rem', color: '#4b5563', cursor: 'pointer' }}>
                <input
                  type="checkbox"
                  checked={config.allowExcessReceiving}
                  onChange={(e) => setConfig(p => ({ ...p, allowExcessReceiving: e.target.checked }))}
                  style={{ width: '16px', height: '16px', accentColor: '#7c7a6e' }}
                />
                <span>Allow excess item quantity receiving above PO order volume limits</span>
              </label>
            </div>

            {config.allowExcessReceiving && (
              <div style={{ display: 'flex', flexDirection: 'column', gap: '6px', maxWidth: '50%', animation: 'fade-in 0.2s ease' }} className="full-width-mobile">
                <label style={{ fontSize: '0.8rem', fontWeight: 600, color: '#4b5563' }}>Maximum Excess Quantity Permitted (%)</label>
                <input
                  type="number"
                  value={config.maxExcessReceivingPercent}
                  onChange={(e) => setConfig(p => ({ ...p, maxExcessReceivingPercent: parseInt(e.target.value) || 0 }))}
                  style={{ padding: '10px', fontSize: '0.875rem', borderRadius: '8px', border: '1px solid #e5e7eb', outline: 'none' }}
                />
              </div>
            )}
          </div>
        )}

        {/* Global form footer actions */}
        <div style={{ display: 'flex', gap: '12px', borderTop: '1px solid #f3f4f6', paddingTop: '16px', justifyContent: 'flex-end' }}>
          <button
            type="button"
            onClick={handleResetDefaults}
            style={{
              padding: '10px 20px',
              fontSize: '0.875rem',
              fontWeight: 600,
              background: '#f3f4f6',
              color: '#4b5563',
              border: '1px solid #e5e7eb',
              borderRadius: '10px',
              cursor: 'pointer'
            }}
          >
            Reset Defaults
          </button>
          
          <button
            type="button"
            onClick={handleSave}
            style={{
              padding: '10px 20px',
              fontSize: '0.875rem',
              fontWeight: 600,
              background: '#7c7a6e',
              color: '#ffffff',
              border: 'none',
              borderRadius: '10px',
              cursor: 'pointer'
            }}
          >
            Save Configurations
          </button>
        </div>

      </div>

      <style>{`
        @media (max-width: 768px) {
          .purchase-config-layout {
            flex-direction: column !important;
          }
          .purchase-config-left {
            width: 100% !important;
          }
          .responsive-grid {
            grid-template-columns: 1fr !important;
          }
        }
      `}</style>

    </div>
  );
}
